variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo_home

cache:
  paths:
    - target/
    - cargo_home/

default:
  image: "rust:1.65.0"
  before_script:
    - rustc --version
    - cargo --version

stages:
  - prepare
  - test
  - build

prepare_node:
  stage: prepare
  script:
    - mkdir -p $CARGO_HOME
    - rustc --version && cargo --version && rustup --version
    - rustup target add x86_64-unknown-linux-musl

test-code:
  stage: test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  coverage: '/^\d+.\d+% coverage/'
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --out Xml

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit-code:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit

build-binary:
  image: "rust:1.65.0-alpine"
  stage: build
  script:
    - apk add libc-dev
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - ./target/x86_64-unknown-linux-musl/release/feeder
      - ./target/x86_64-unknown-linux-musl/release/alarms-dispatcher
