variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo_home

cache:
  paths:
    - target/
    - cargo_home/

default:
  image: "rust:1.64-alpine"
  before_script:
    - rustc --version
    - cargo --version

stages:
  - prepare
  - test
  - build

prepare_node:
  stage: prepare
  script:
    - apk add musl-dev
    - mkdir -p $CARGO_HOME
    - rustc --version && cargo --version && rustup --version

test-code:
  stage: test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  coverage: '/^\d+.\d+% coverage/'
  script:
    - apk add openssl-dev
    - cargo test --target x86_64-unknown-linux-musl
    - cargo install cargo-tarpaulin --target x86_64-unknown-linux-musl
    - cargo tarpaulin --target x86_64-unknown-linux-musl --ignore-tests --out Xml

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit-code:
  stage: test
  script:
    - cargo install cargo-audit --target x86_64-unknown-linux-musl
    - cargo audit

build-binary:
  stage: build
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - ./target/release/feeder
