poll_period_seconds = 60

[node]
json_rpc_protocol = "https"
grpc_protocol = "https"
#http2_concurrency_limit = 1
host = "net-dev.nolus.io"
json_rpc_port = 26617
# json_rpc_api_path = "/json-rpc/api"
grpc_port = 26620
# grpc_api_path = "/grpc/api"
address_prefix = "nolus"
chain_id = "nolus-dev-v0-1-42"
fee = { amount = "1500", denom = "unls" }
gas_adjustment_numerator = 10175
gas_adjustment_denominator = 10000

[time_alarms]
address = "nolus1zwv6feuzhy6a9wekh96cd57lsarmqlwxdypdsplw6zhfncqw6ftqmx7chl"
max_alarms_group = 16
gas_limit_per_alarm = 500_000

[market_price_oracle]
address = "nolus1436kxs0w2es6xlqpp9rd35e3d0cjnw4sv8j3a7483sgks29jqwgsv3wzl4"
max_alarms_group = 16
gas_limit_per_alarm = 500_000
