[workspace]
members = [
    "semver",
    "chain-comms",
    "market-data-feeder",
    "alarms-dispatcher",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
semver = { path = "./semver" }
chain-comms = { path = "./chain-comms" }

[patch.crates-io]
tendermint = { git = "https://github.com/nolus-protocol/tendermint-rs.git", branch = "feat-set-origin-header" }
tendermint-proto = { git = "https://github.com/nolus-protocol/tendermint-rs.git", branch = "feat-set-origin-header" }
tendermint-rpc = { git = "https://github.com/nolus-protocol/tendermint-rs.git", branch = "feat-set-origin-header" }

[profile.release]
overflow-checks = true
lto = "fat"
