[workspace]
resolver = "2"

members = ["chain-comms", "market-data-feeder", "alarms-dispatcher", "broadcast"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
broadcast = { path = "./broadcast" }
chain-comms = { path = "./chain-comms" }

astroport = "3.6.1"
async-trait = "0.1.77"
base64 = "0.21.5"
bip32 = { version = "0.5.1", features = ["mnemonic"] }
bnum = "0.10.0"
bytes = "1.5.0"
cosmrs = { version = "=0.14.0", default-features = false, features = [
    "rpc",
    "grpc",
    "bip32",
    "cosmwasm",
] }
futures = "0.3.30"
http = { version = "=0.2.11", default-features = false }
osmosis-std = "=0.20.1"
prost = "=0.11.9"
prost-types = "=0.11.9"
regex = "1.10.2"
reqwest = { version = "0.11.23", default-features = false, features = [
    "json",
    "rustls-tls",
] }
semver = { version = "1.0.21", features = ["serde"] }
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
serde-json-wasm = "1.0.0"
time = { version = "0.3.31", default-features = false, features = [
    "std",
    "formatting",
] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
toml = "0.8.8"
tonic = { version = "=0.9.2", default_features = false, features = [
    "tls",
    "tls-roots",
    "gzip",
] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
url = { version = "2.5.0", default-features = false }

[patch.crates-io.tendermint]
git = "https://github.com/nolus-protocol/tendermint-rs.git"
branch = "feat-set-origin-header"

[patch.crates-io.tendermint-proto]
git = "https://github.com/nolus-protocol/tendermint-rs.git"
branch = "feat-set-origin-header"

[patch.crates-io.tendermint-rpc]
git = "https://github.com/nolus-protocol/tendermint-rs.git"
branch = "feat-set-origin-header"

[profile.release]
overflow-checks = true
lto = "fat"
