[workspace]
members = [
    "market-data-feeder",
    "alarms-dispatcher",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[profile.release]
overflow-checks = true
lto = "fat"
