[package]
name = "market-data-feeder"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "feeder"

[dependencies]
# [...]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }

secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
confy = "0.4.0"
toml = "0.5"
thiserror = "1.0.30"
async-trait = "0.1.53"
tonic = { version = "0.7.2", features = ["compression", "tls", "tls-roots"]}
prost = { version = "0.10.1"}
prost-types = { version = "0.10.1" }


# finance = { path = "../smart-contracts/packages/finance", version = "0.1.0", default-features = false }
# finance = { git = "https://gitlab-nomo.credissimo.net/nomo/smart-contracts", package = "finance", version = "0.1.0", default-features = false }



# cosmos sdk clients
cosmrs = {version = "0.7.0", features = ["cosmwasm", "rpc"]}
cosmos-sdk-proto = {version = "0.12.3", features = ["cosmwasm", "grpc-transport"]}



[dev-dependencies]
# [...]
tokio = { version = "1", features = ["rt", "macros"] }
wiremock = "0.5.2"
actix-rt = "2.7.0"
cosmrs = {version = "0.7.0", features = ["cosmwasm", "rpc", "dev"]}

