hard_tabs = false
match_block_trailing_comma = true
max_width = 80
newline_style = "unix"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true

# unstable... should we require `rustup run nightly cargo fmt` ?
# or just update the style guide when they are stable?
#fn_single_line = true
#format_code_in_doc_comments = true
#overflow_delimited_expr = true
#reorder_impl_items = true
#struct_field_align_threshold = 20
#struct_lit_single_line = true
#report_todo = "Always"
