[package]
name = "alarms-dispatcher"
version = "0.1.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cosmrs = { version = "0.11", default-features = false, features = ["rpc", "grpc", "bip32", "cosmwasm"] }
prost = { version = "0.11.2", default-features = false, features = ["std"] }
thiserror = "1"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "io-std", "io-util", "time", "fs"] }
toml = "0.5"
tonic = { version = "0.8.2", default_features = false, features = ["tls", "gzip"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.16"
serde = { version = "1", features = ["derive"] }
serde-json-wasm = "0.5"
