admin_contract = "nolus1ghd753shjuwexxywmgs4xz7x2q732vcnkm6h2pyv9s6ah3hylvrq8welhp"

[broadcast]
tick_time_seconds = 60
poll_time_seconds = 15
between_tx_margin_seconds = 5

[node]
address_prefix = "nolus"
fee_denom = "unls"
#gas_adjustment_numerator = 10125
#gas_adjustment_denominator = 10000
gas_adjustment_numerator = 12
gas_adjustment_denominator = 10
gas_price_numerator = 1
gas_price_denominator = 390
fee_adjustment_numerator = 5
fee_adjustment_denominator = 1

[time_alarms]
max_alarms_group = 32
gas_limit_per_alarm = 750_000

[market_price_oracle]
max_alarms_group = 16
gas_limit_per_alarm = 750_000
