tick_time_seconds = 60
poll_time_seconds = 15
between_tx_margin_seconds = 5

[node]
address_prefix = "nolus"
chain_id = "rila-1"
fee_denom = "unls"
#gas_adjustment_numerator = 10125
#gas_adjustment_denominator = 10000
gas_adjustment_numerator = 2
gas_adjustment_denominator = 1
gas_price_numerator = 1
gas_price_denominator = 390
fee_adjustment_numerator = 5
fee_adjustment_denominator = 1

[[time_alarms]]
address = "nolus1zwv6feuzhy6a9wekh96cd57lsarmqlwxdypdsplw6zhfncqw6ftqmx7chl"
max_alarms_group = 32
#gas_limit_per_alarm = 175_000
gas_limit_per_alarm = 5_000_000

[[market_price_oracle]]
address = "nolus13je4ss56rctm6wazddgch7j6qljkcm8k9uel6nnnr3kllke8e4yqczygxr"
max_alarms_group = 16
gas_limit_per_alarm = 5_000_000

[[market_price_oracle]]
address = "nolus1avgvt4mu0tzad09y4nmaw53av9ulqz6yyu78ty82stntv8qy7s8s8e4qrf"
max_alarms_group = 16
gas_limit_per_alarm = 5_000_000
