hard_gas_limit = 10_000_000

[broadcast]
tick_time_seconds = 60
poll_time_seconds = 15
between_tx_margin_seconds = 2

[node]
address_prefix = "nolus"
fee_denom = "unls"
gas_adjustment_numerator = 2
gas_adjustment_denominator = 1
gas_price_numerator = 1
gas_price_denominator = 390
fee_adjustment_numerator = 5
fee_adjustment_denominator = 1

[oracles]
osmosis-osmosis-usdc_axelar = "nolus1436kxs0w2es6xlqpp9rd35e3d0cjnw4sv8j3a7483sgks29jqwgsv3wzl4"
osmosis-osmosis-usdc_noble = "nolus1vjlaegqa7ssm2ygf2nnew6smsj8ref9cmurerc7pzwxqjre2wzpqyez4w6"
neutron-astroport-usdc_axelar = "nolus1jew4l5nq7m3xhkqzy8j7cc99083m5j8d9w004ayyv8xl3yv4h0dql2dd4e"

[providers.osmosis_osmosis_usdc_axelar]
name = "osmosis"
oracle_id = "osmosis-osmosis-usdc_axelar"

[providers.osmosis_osmosis_usdc_noble]
name = "osmosis"
oracle_id = "osmosis-osmosis-usdc_noble"

[providers.neutron_astroport_usdc_axelar]
name = "astroport"
oracle_id = "neutron-astroport-usdc_axelar"

[comparison_providers]
