hard_gas_limit = 1_000_000

[oracles]
osmosis-osmosis-usdc_axelar = "nolus1ldu3nwcvaqwwfk5za68xpwt4zzsjd74vl8ezx99hhk9rs7lslsvsgq7mm4"
neutron-astroport-usdc_axelar = "nolus1xzdk79z2gtq5vevs2edzyjaw8ue2vf2qmaecu6hyxcr3mwgfchtq8dyfk9"

[providers.osmosis_osmosis_usdc_axelar]
name = "osmosis"
oracle_id = "osmosis-osmosis-usdc_axelar"

[providers.neutron_astroport_usdc_axelar]
name = "astroport"
oracle_id = "neutron-astroport-usdc_axelar"

[comparison_providers]
